### ISSUE TITLE
OpenSSl error

### ISSUE THREAD

**Issue by Tiflo62** [dedshit/metasploit_in_termux#5]
Hello, 

After a fail during the installation with the gushmazuko way, I used your fork. Installed successfully but openssl error.

![Screenshot_20220416_225722_com termux](https://user-images.githubusercontent.com/74988027/163691173-a7bd6655-178e-4656-9b02-2413adc45d21.jpg)
![Screenshot_20220416_225728_com termux](https://user-images.githubusercontent.com/74988027/163691174-c0742d00-476c-4b25-871e-f0c5007d074f.jpg)
![Screenshot_20220416_225735_com termux](https://user-images.githubusercontent.com/74988027/163691176-f76d3bb3-e781-477d-b671-8053ab6a08a7.jpg)

**Comment by dedshit** [comment]
let me release my package do u have open source site to host deb package?
