### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zhengyo** [dedshit/metasploit_in_termux#7]
![Screenshot_20220503_010215_com termux](https://user-images.githubusercontent.com/95407088/166291970-59af3ab7-7f6e-42fe-b899-fc5aa3923add.jpg)

**Comment by dedshit** [comment]
send ss of nokogiri version  and gemfile.lock you may find that in opt

**Comment by dedshit** [comment]
> ![Screenshot_20220503_010215_com termux](https://user-images.githubusercontent.com/95407088/166291970-59af3ab7-7f6e-42fe-b899-fc5aa3923add.jpg)

did u try to overwrite existing one ?

**Comment by dedshit** [comment]
did u see any error before that

**Comment by dedshit** [comment]
fixed
